import { ClassSpec, SoldierClass } from "./types";

export const CLASSES: Record<SoldierClass, ClassSpec> = {
  assault: {
    id: "assault",
    name: "ASSAULT",
    hpMax: 100,
    speedMult: 1.0,
    primary: "rifle",
    secondary: "pistol",
    grenadeCount: 3,
    smokeCount: 1,
    ability: "Adrenaline",
    abilityDesc: "標準的な兵士。バランスの取れた装備。",
  },
  sniper: {
    id: "sniper",
    name: "SNIPER",
    hpMax: 80,
    speedMult: 0.9,
    primary: "sniper",
    secondary: "pistol",
    grenadeCount: 1,
    smokeCount: 2,
    ability: "Steady Aim",
    abilityDesc: "遠距離特化。高ダメージ・低HP。",
  },
  support: {
    id: "support",
    name: "SUPPORT",
    hpMax: 130,
    speedMult: 0.85,
    primary: "smg",
    secondary: "pistol",
    grenadeCount: 4,
    smokeCount: 2,
    ability: "Ammo Supply",
    abilityDesc: "高耐久・弾薬多め。味方に弾薬補給。",
  },
  medic: {
    id: "medic",
    name: "MEDIC",
    hpMax: 90,
    speedMult: 1.1,
    primary: "smg",
    secondary: "pistol",
    grenadeCount: 2,
    smokeCount: 3,
    ability: "Heal Aura",
    abilityDesc: "移動速度UP。周囲の味方を回復。",
  },
};
